using System;
using System.Collections.Generic;
namespace Bot
{
    public class Openings
    {
        public List<List<string>> openings = new List<List<string>>();
        public int openingIndex;

        public Openings()
        {
            openingIndex = 0;
            openings = new List<List<string>>
            {
                new List<string> {"e4", "e5", "d4", "exd4", "c3"},
                new List<string> {"e4"},
                new List<string> {"d4"},
                new List<string> {"g3"},
                new List<string> {"b3"},
                new List<string> {"c4"},
                new List<string> {"f4"},
                new List<string> {"Nf3"},
                new List<string> {"c4", "c5"},
                new List<string> {"d4", "d5"},
                new List<string> {"c4", "e5"},
                new List<string> {"d4", "g6"},
                new List<string> {"e4", "d6"},
                new List<string> {"d4", "c5"},
                new List<string> {"e4", "c6"},
                new List<string> {"e4", "e6"},
                new List<string> {"e4", "Nf6"},
                new List<string> {"e4", "d5"},
                new List<string> {"e4", "c5"},
                new List<string> {"e4", "c5", "c3"},
                new List<string> {"e4", "c5", "d4"},
                new List<string> {"e4", "e5", "Bc4"},
                new List<string> {"e4", "c5", "Nc3"},
                new List<string> {"d4", "d5", "e4"},
                new List<string> {"d4", "Nf6", "Bg5"},
                new List<string> {"e4", "c5", "d4"},
                new List<string> {"e4", "c5", "Nc3"},
                new List<string> {"Nf3", "d5", "c4"},
                new List<string> {"d4", "Nf6", "Bg5"},
                new List<string> {"e4", "e5", "f4", "d5"},
                new List<string> {"d4", "d5", "c4", "Nc6"},
                new List<string> {"e4", "e5", "Nf3", "d6"},
                new List<string> {"d4", "Nf6", "c4", "d6"},
                new List<string> {"d4", "d5", "c4", "e5"},
                new List<string> {"e4", "d5", "exd5", "Nf6"},
                new List<string> {"d4", "Nf6", "c4", "e5"},
                new List<string> {"d4", "f5", "e4", "fxe4"},
                new List<string> {"e4", "e5", "f4", "Bc5"},
                new List<string> {"e4", "e5", "Nf3", "Nf6"},
                new List<string> {"d4", "Nf6", "c4", "g6"},
                new List<string> {"d4", "d5", "c4", "c6"},
                new List<string> {"d4", "d5", "c4", "dxc4"},
                new List<string> {"e4", "e5", "f4", "exf4"},
                new List<string> {"d4", "d5", "Nf3", "Nf6", "Bf4"},
                new List<string> {"d4", "d5", "Nf3", "Nf6", "Bg5"},
                new List<string> {"e4", "e6", "d4", "d5", "e5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "d4"},
                new List<string> {"e4", "e6", "d4", "d5", "Nd2"},
                new List<string> {"e4", "c6", "d4", "d5", "e5"},
                new List<string> {"e4", "c5", "Nc3", "Nc6", "f4"},
                new List<string> {"e4", "e5", "f4", "exf4", "Bc4"},
                new List<string> {"e4", "c6", "d4", "d5", "exd5"},
                new List<string> {"e4", "e5", "Nf3", "Nf6", "Nc3"},
                new List<string> {"e4", "e6", "d4", "d5", "exd5"},
                new List<string> {"e4", "e5", "Nf3", "Nf6", "d4"},
                new List<string> {"d4", "d5", "Nf3", "Nf6", "Bg5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Nc3", "Nf6"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "Bg7"},
                new List<string> {"e4", "e6", "d4", "d5", "Nc3", "Bb4"},
                new List<string> {"d4", "Nf6", "c4", "e6", "Nc3", "Bb4"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "d5"},
                new List<string> {"d4", "Nf6", "c4", "c5", "d5", "e6"},
                new List<string> {"d4", "Nf6", "c4", "c5", "d5", "b5"},
                new List<string> {"d4", "Nf6", "c4", "e6", "Nf3", "b6"},
                new List<string> {"e4", "e6", "d4", "d5", "Nc3", "Nf6"},
                new List<string> {"e4", "e5", "f4", "exf4", "Nf3", "d5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "f5"},
                new List<string> {"e4", "g6", "d4", "Bg7", "Nc3", "c5"},
                new List<string> {"e4", "e6", "d4", "d5", "Nc3", "dxe4"},
                new List<string> {"d4", "Nf6", "c4", "e6", "Nf3", "Bb4+"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "d6"},
                new List<string> {"d4", "d5", "c4", "e6", "Nf3", "c5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "Bc5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bc4", "Be7"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "b4"},
                new List<string> {"e4", "c6", "d4", "d5", "exd5", "cxd5", "c4"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Nc3", "Nf6", "d4"},
                new List<string> {"d4", "Nf6", "c4", "e6", "g3", "d5", "Bg2"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Bxc6"},
                new List<string> {"e4", "d6", "d4", "Nf6", "Nc3", "g6", "Nf3"},
                new List<string> {"e4", "d6", "d4", "Nf6", "Nc3", "g6", "f4"},
                new List<string> {"d4", "Nf6", "c4", "e6", "Nc3", "Bb4", "Qc2"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "d5", "Bg5"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "d5", "Nf3"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "d5", "Bf4"},
                new List<string> {"e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4"},
                new List<string> {"e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Bf5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5"},
                new List<string> {"d4", "d5", "c4", "e6", "Nc3", "Nf6", "Nf3", "c5"},
                new List<string> {"d4", "d5", "c4", "e6", "Nc3", "Nf6", "Nf3", "c6"},
                new List<string> {"e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "Nc6"},
                new List<string> {"e4", "e6", "d4", "d5", "Nc3", "Nf6", "Bg5", "dxe4"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Qh4"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "d5", "cxd5", "Nxd5"},
                new List<string> {"d4", "Nf6", "c4", "e6", "Nc3", "Bb4", "e3", "c5"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "Nf3", "d6", "g3"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f4"},
                new List<string> {"e4", "e5", "Nf3", "Nf6", "Nxe5", "d6", "Nf3", "Nxe4", "d4"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3"},
                new List<string> {"c4", "f5", "Nf3", "Nf6", "d4", "g6", "g3", "Bg7", "Bg2"},
                new List<string> {"d4", "Nf6", "c4", "e6", "Nc3", "Bb4", "a3", "Bxc3+", "bxc3"},
                new List<string> {"d4", "Nf6", "c4", "e6", "Nc3", "Bb4", "e3", "c5", "Ne2"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "Nc6", "Bg5"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Be2", "O-O", "Bg5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nf6", "Nxc6", "bxc6", "e5"},
                new List<string> {"d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Be7", "e3", "O-O Nf3", "Nbd7"},
                new List<string> {"d4", "f5", "c4", "Nf6", "g3", "e6", "Bg2", "Be7", "Nf3", "O-O", "O-O", "d5"},
                new List<string> {"d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "O-O", "Nc6", "d5", "Ne7", "b4"},
                // Openings from Encyclopaedia of Chess Openings (ECO) A00-A99 without dublicits
                // from https://www.chessarch.com/library/0000_eco/a00_a99.shtml got with the help of chatgpt 
                new List<string> {"b4"},
                new List<string> {"b3"},
                new List<string> {"f4", "d5"},
                new List<string> {"Nf3", "Nf6"},
                new List<string> {"Nf3", "d5", "g3", "c5", "Bg2"},
                new List<string> {"Nf3", "d5", "c4"},
                new List<string> {"c4", "c6", "Nf3"},
                new List<string> {"c4", "e6", "Nc3"},
                new List<string> {"c4", "Nf6", "Nc3", "e6", "e4", "c5", "e5", "Ng8"},
                new List<string> {"c4", "e5", "Nc3", "Nf6", "g3", "c6"},
                new List<string> {"c4", "e5", "Nc3", "Nc6", "g3"},
                new List<string> {"c4", "e5", "Nc3", "Nf6", "g3", "Bb4", "Bg2", "O-O"},
                new List<string> {"c4", "e5", "Nc3", "Nf6", "g3", "g6"},
                new List<string> {"c4", "c5", "Nf3", "Nf6", "d4"},
                new List<string> {"c4", "c5", "Nc3", "Nc6", "g3", "Bg7"},
                new List<string> {"c4", "c5", "Nc3", "Nc6", "g3", "g6", "Bg2", "Bg7", "d3", "d6"},
                new List<string> {"d4", "d6", "e4", "g6"},
                new List<string> {"d4", "c5", "d5", "e5"},
                new List<string> {"d4", "Nf6", "Nf3", "b6"},
                new List<string> {"d4", "Nf6", "Nf3", "g6", "g3"},
                new List<string> {"d4", "Nf6", "c4", "e5", "dxe5", "Ng4"},
                new List<string> {"d4", "Nf6", "c4", "d6", "Nc3", "e5"},
                new List<string> {"d4", "Nf6", "c4", "d6", "Nc3", "Nbd7"},
                new List<string> {"d4", "Nf6", "c4", "c5", "d5", "b5", "cxb5", "a6", "bxa6", "Bxa6"},
                new List<string> {"d4", "Nf6", "c4", "c5", "d5", "e6", "Nc3", "d6"},
                new List<string> {"d4", "Nf6", "c4", "c5", "d5", "e6", "Nf3", "exd5", "cxd5", "d6", "g3", "g6", "Bg2", "Bg7"},
                new List<string> {"d4", "Nf6", "c4", "c5", "d5", "e6", "Nc3", "exd5", "cxd5", "d6", "e4", "g6", "Nf3", "Bg7", "Be2", "O-O", "O-O"},
                new List<string> {"d4", "Nf6", "c4", "c5", "d5", "e6", "Nc3", "exd5", "cxd5", "d6", "e4", "g6", "f4", "Bg7", "Nf3", "O-O", "Be2", "Re8"},
                new List<string> {"d4", "Nf6", "c4", "c5", "d5", "e6", "Nc3", "exd5", "cxd5", "d6", "Nf3", "g6", "e4", "Bg7", "Be2", "O-O", "O-O", "Re8", "Nd2", "Nbd7"},
                new List<string> {"d4", "Nf6", "c4", "c5", "d5", "e6", "Nc3", "exd5", "cxd5", "d6", "Nf3", "g6", "e4", "Bg7", "Be2", "O-O", "O-O", "Re8", "Nd2", "a6", "a4", "Qa5"},
                new List<string> {"d4", "Nf6", "c4", "c5", "d5", "e6", "Nc3", "exd5", "cxd5", "d6", "Nf3", "g6", "e4", "Bg7", "Be2", "O-O", "O-O", "Re8", "Nd2", "a6", "a4", "b5"},
                new List<string> {"d4", "f5", "g3", "Nf6", "Bg2"},
                new List<string> {"d4", "f5", "c4", "Nf6", "g3", "g6", "Bg2", "Bg7", "Nf3", "O-O"},
                new List<string> {"d4", "f5", "c4", "Nf6", "g3", "e6", "Bg2", "Be7", "Nf3", "O-O", "O-O", "d6", "Nc3", "Qe8", "Qc2", "Nc6", "Rd1", "e5"},
                // Openings from Encyclopaedia of Chess Openings (ECO) B00-B99 without dublicits
                // from https://www.chessarch.com/library/0000_eco/b00_b99.shtml got with the help of chatgpt 
                new List<string> {"e4", "d5"},
                new List<string> {"e4", "Nf6", "e5", "Nd5", "d4", "d6", "Nf3"},
                new List<string> {"e4", "g6"},
                new List<string> {"e4", "d6", "d4", "Nf6", "Nc3", "g6", "Be3"},
                new List<string> {"e4", "c6", "d4", "d5", "Nd2", "dxe4", "Nxe4", "Nf6"},
                new List<string> {"e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nf6", "Nxf6+", "gxf6"},
                new List<string> {"e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Nd7"},
                new List<string> {"e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Bf5", "Ng3", "Bg6"},
                new List<string> {"e4", "c5", "f4"},
                new List<string> {"e4", "c5", "Nc3", "Nc6", "Nf3", "e6", "d4", "cxd4", "Nxd4", "a6"},
                new List<string> {"e4", "c5", "Nf3", "a6", "d4", "cxd4", "Nxd4"},
                new List<string> {"e4", "c5", "Nf3", "Nc6", "Bb5"},
                new List<string> {"e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "e5", "Nxc6"},
                new List<string> {"e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "d6", "Bg5"},
                new List<string> {"e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "Nf6"},
                new List<string> {"e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "Nc6", "Nc3", "a6"},
                new List<string> {"e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "Nc6", "Nc3", "Qc7", "Be2", "a6"},
                new List<string> {"e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "Nc6", "Nc3", "Qc7", "Be2", "Nf6", "O-O"},
                new List<string> {"e4", "c5", "Nf3", "d6", "Bb5+", "Bd7"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Qxd4"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "Nc6", "Be2", "e5", "Nb3"},
                new List<string> {"e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "d6", "Nc3", "Nf6", "Bg5", "e6", "f4", "Qb6", "Nb3", "Be7", "Qf3"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "Nf6", "Nc3", "e5", "Nb3", "Be6", "Bg5", "Be7", "f4"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "Nf6", "Nc3", "Nc6", "Ndb5", "d6", "Bg5", "a6", "Na3", "b5", "Bxf6", "gxf6"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e6", "g4"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e6", "f4", "Nc6"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e6", "Be2", "Nc6"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e6", "Be2", "a6"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e6", "Be2", "Be7", "O-O", "O-O", "f4", "Nc6"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6", "Be2"},
                new List<string> {"e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6", "Bg5", "e6", "f4", "Be7", "Qf3", "Qc7", "O-O-O", "Nbd7", "g4"},
                // Openings from Encyclopaedia of Chess Openings (ECO) C00-C99 without dublicits
                // from https://www.chessarch.com/library/0000_eco/c00_c99.shtml got with the help of chatgpt 
                new List<string> {"e4", "e6", "d4", "d5", "exd5", "exd5"},
                new List<string> {"e4", "e6", "d4", "d5", "e5"},
                new List<string> {"e4", "e6", "d4", "d5", "Nd2", "Nc6"},
                new List<string> {"e4", "e6", "d4", "d5", "Nd2", "Nf6", "e5", "Nfd7"},
                new List<string> {"e4", "e6", "d4", "d5", "Nd2", "Nf6", "exd5", "exd5", "Ngf3", "Be7", "Bd3", "O-O"},
                new List<string> {"e4", "e6", "d4", "d5", "Nc3", "Nf6", "e5", "Nfd7"},
                new List<string> {"e4", "e6", "d4", "d5", "Nc3", "Nf6", "Bg5", "Bb4"},
                new List<string> {"e4", "e6", "d4", "d5", "Nc3", "Nf6", "Bg5", "dxe4", "Nxe4", "Be7"},
                new List<string> {"e4", "e6", "d4", "d5", "Nc3", "Bb4", "e5", "Ne7"},
                new List<string> {"e4", "e6", "d4", "d5", "Nc3", "Bb4", "e5", "c5", "a3", "Bxc3+", "bxc3", "Ne7", "Qg4", "Ne7", "Qxg7", "Rg8", "Qxh7"},
                new List<string> {"e4", "e5", "d4", "exd4", "c3"},
                new List<string> {"e4", "e5", "Bc4", "Nf6"},
                new List<string> {"e4", "e5", "Nc3", "Nf6", "f4", "d5", "exd5", "Nxd5", "Qh5"},
                new List<string> {"e4", "e5", "Nc3", "Nc6", "f4"},
                new List<string> {"e4", "e5", "f4", "d5", "exd5", "exf4"},
                new List<string> {"e4", "e5", "f4", "exf4", "Nf3", "Be7"},
                new List<string> {"e4", "e5", "f4", "exf4", "Nf3", "d5"},
                new List<string> {"e4", "e5", "f4", "exf4", "Nf3", "Nf6"},
                new List<string> {"e4", "e5", "f4", "exf4", "Nf3", "g5", "Bc4"},
                new List<string> {"e4", "e5", "f4", "exf4", "Nf3", "g5", "h4", "g4", "Ng5"},
                new List<string> {"e4", "e5", "Nf3", "d6"},
                new List<string> {"e4", "e5", "Nf3", "Nf6", "d4"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "d4"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Nc3", "Nf6", "Bb5", "Bb4"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "b4", "Bxb4", "c3", "Ba5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+", "Nc3", "Nxe4"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4", "exd4", "O-O"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "Bc5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Na5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "Nd4"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "d6"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "f5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "Bc5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6", "O-O", "d6"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6", "O-O", "Nxe4"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Bxc6", "dxc6", "O-O", "Bg4", "h3", "h5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "d6", "c3", "Bd7", "O-O", "Nge7"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "d6", "c3", "Bd7", "O-O", "g6"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "d6", "c3", "Bd7", "Re1", "b5", "Bb3", "Nf6"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "d6"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Nxe4", "d4", "b5", "Bb3", "d5", "dxe5", "Be6", "c3", "Be7"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Be7", "Qe2"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Be7", "c3", "d5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Be7", "Re1", "b5", "Bb3", "O-O", "c3", "d5"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Be7", "Re1", "d6", "c3", "O-O", "h3", "Nb8"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Be7", "Re1", "d6", "c3", "O-O", "h3", "Bb7"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Be7", "Re1", "b5", "Bb3", "d6", "c3", "O-O", "h3", "h6"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Be7", "Re1", "b5", "Bb3", "d6", "c3", "O-O", "h3", "Nb8", "d4", "Nd7", "Nbd2", "Bb7", "Nf1", "Re8"},
                new List<string> {"e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Be7", "Re1", "b5", "Bb3", "d6", "c3", "O-O", "h3", "Nb8", "d4", "Nd7", "Nbd2", "Bb7", "Nf1", "exd4"}
            };
        }

        public (string, bool) CheckOpening(List<string> moves)
        {
            List<string> nextMoves = new List<string>();
            for(int i = 0; i < openings.Count; i++)
            {
                for(int j = 0; j < moves.Count; j++)
                {
                    if(openings[i].Count <= moves.Count || openings[i][j] != moves[j])
                    {
                        break;
                    }
                    if(j == moves.Count - 1 && openings[i].Count > moves.Count)
                    {
                        openingIndex = i;
                        nextMoves.Add(openings[i][j+1]);
                        break;
                        // return (openings[i][j+1], true);
                    }
                }
            }
            if(nextMoves.Count > 0)
            {
                Random random = new Random();
                int index = random.Next(0,nextMoves.Count-1);
                return (nextMoves[index], true);
            }
            return ("", false);
        }
    }
}